language: go

go:
  - "1.11.x"

os:
  - linux
  - osx

sudo: false

addons:
  apt:
    packages:
      - gobjc
      - gnustep
      - gnustep-devel

install:
  - env GO111MODULE=on go get ./...

script:
  - env GO111MODULE=on go test -v ./...
